package com.star.sud.publisher;

import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;

import reactor.core.publisher.Mono;

@Component
public class GreetingHandler {

	/**
	 * This simple reactive class always returns "Hello, Spring!" It could return
	 * many other things, including a stream of items from a database, a stream of
	 * items that were generated by calculations, and so on. Note the reactive code:
	 * a Mono object that holds a ServerResponse body.
	 */
	public Mono<ServerResponse> hello(ServerRequest request) {
		return ServerResponse.ok().contentType(MediaType.TEXT_PLAIN).body(BodyInserters.fromValue("Hello, String"));
	}

}
